# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build all fonts

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install -g yarn
    - run: npm install
    - run: npm test
    
    - name: Build all fonts
      run: ./bin/run.sh
        
    - name: Zip all artifacts for release
      run: zip -9 -j build/all_fonts.zip build/*.ttf
        
    - name: Create a new release draft
      id: create_release
      uses: ncipollo/release-action@v1
      with:
          artifacts: "build/all_fonts.zip"
          body: If you can read this, we have forgotten to fill in the changelog. Sorry!
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          draft: true
          name: Release ${{ github.ref }}

